### ISSUE TITLE
Remover Whatsapp do site

### ISSUE THREAD

**Issue by yurikoster1** [pixhausdigital/Bem-a-Bordo#1]
O whatsapp não permite mandar mensagens para um contato não incluído previamente nos contatos do cliente então um ícone do whatsapp não seria confiável para mandar mensagens.

![image](https://cloud.githubusercontent.com/assets/2926881/20506375/b86ad714-b03a-11e6-9ffb-6cc9093c65e6.png)

**Comment by Mauroletizia** [comment]
Blz, Valeu!
