### ISSUE TITLE
aumentar o espaçamento entre cada texto descritivo das pessoas

### ISSUE THREAD

**Issue by Mauroletizia** [pixhausdigital/Bem-a-Bordo#22]

**Comment by yurikoster1** [comment]
preciso de mais descrição. espaçamento lateral e horizontal? aumentar por quanto? uma imagem de referencia ajudaria

**Comment by Mauroletizia** [comment]
Aumentar o espaço vertical entre eles, aumentar a largura do espaço entre eles
