### ISSUE TITLE
Aumentar os espaços das entrelinhas em geral

### ISSUE THREAD

**Issue by Mauroletizia** [pixhausdigital/Bem-a-Bordo#7]

**Comment by yurikoster1** [comment]
preciso de uma descrição melhor talvez uma imagem ilustrativa?

**Comment by Mauroletizia** [comment]
Aumentar o espaço das entrelinhas dos blocos de texto:
![espaco maior - ok](https://cloud.githubusercontent.com/assets/22946583/21535407/a68a1062-cd5b-11e6-9389-ff8691caaab8.jpg)
![espaco pequeno](https://cloud.githubusercontent.com/assets/22946583/21535408/a68aee1a-cd5b-11e6-9cd6-b77b63563927.jpg)
