### ISSUE TITLE
Atualidades: fixar a altura das imagens. Se a imagem for muito larga, crop na largura. Se for muito alta, sobra branco do lado. Alinhar pelo lado esquerdo, com o texto, igual as fotos do "quem somos"

### ISSUE THREAD

**Issue by Mauroletizia** [pixhausdigital/Bem-a-Bordo#9]

**Comment by yurikoster1** [comment]
[definir qual a proporção que vamos usar nas imagens ](http://photo.stackexchange.com/questions/33713/most-common-aspect-ratio)

>The two most common aspect ratios are 4:3 and 3:2. You will also see a significant number of 1:1 (square) photos and 16:9 ("widescreen") images.
3:2 is the aspect ratio of 35mm film cameras, and that has carried over to most DSLRs, both the APS-C size and "full-frame". Most compact digital cameras, along with the Micro Four Thirds interchangeable-lens mirrorless system, use 4:3.
Most smartphones are also normally 4:3, but popular apps like Instagram and Hipstamatic produce square 1:1 images, so you can't discount that. And, the HDTV-like 16:9 aspect ratio is a common option in many cameras of all types (usually but not always just by cropping off the top and bottom of each image in-camera).
It would probably also be wise to consider the possibility of arbitrarily-wide panoramic images, as many cameras (both via apps and just as a feature) have the ability to produce those very easily. And, of course, you really shouldn't discount cropping, both to historically-standard ratios like 8:10 and 5:7, and completely arbitrarily.
And keep in mind that you will also see these turned the other way: 3:4 and 2:3 for portraits; 9:16 looks odd and is less likely, but the theme here really is that anything goes.
This is all off of the top of my head, but if you'd like the referenced and researched background on these aspect ratios and other common ones found in photography, see my answer to [What historic reasons are there for common aspect ratios](http://photo.stackexchange.com/questions/15298/what-historic-reasons-are-there-for-common-aspect-ratios)?

**Comment by Mauroletizia** [comment]
Acho que um aspecto de 0,75 (800x600, 1024x768...) ou 4x3, é um padrão

**Comment by Mauroletizia** [comment]
![noticia](https://cloud.githubusercontent.com/assets/22946583/21535548/c6a30000-cd5d-11e6-86ed-b00e4c170277.jpg)
